micronaut:
  application:
    name: finance
  data:
    pageable:
      default-page-size: 10
      max-page-size: 50
      sort-ignore-case: true
      sort-parameter-name: orderBy
      size-parameter-name: size
      page-parameter-name: page
      sort-delimiter: ','
  server:
    cors:
      enabled: true


datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://postgres:5432/finance`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:finance}
    password: ${DB_PASSWORD:password}
    schema-generate: CREATE_DROP
    dialect: PostgreSQLDialect
jpa.default.properties.hibernate.hbm2ddl.auto: update




